language: python
puthon: 3.8
script:
- cd LW06
- pytest
- cd ..

deploy:
provider: releases
prerelease: true
api_key: $GITHUB_TOKEN
skip_cleanup: true
on:
repo: FedorovaElena/LW06
branch: dev
tags: false
